# Generated by Django 3.0.7 on 2021-02-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_karma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='karma',
        ),
    ]
