# Generated by Django 3.0.7 on 2021-02-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likeProduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likeProduct', to='products.Product'),
        ),
    ]
