# Generated by Django 3.0.7 on 2021-02-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0006_like_likeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=255)),
                ('commentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to='profiles.Profile')),
                ('commentProduct', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commentProduct', to='products.Product')),
            ],
        ),
    ]
